name: CI/CD for Puppet Bolt

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run setup script for puppet bolt
        run: ./setup.sh

      # Runs a set of commands using the runners shell
      - name: Add Private Key
        run: |
          cat << EOF > id_rsa.pem
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOF
      - name: Add Inventory File
        run: |
          cat << EOF > inventory.yaml
          groups:
            - name: webapps
              targets:
                - ${{ secrets.LINODE_WEBAPP_A }}
                - ${{ secrets.LINODE_WEBAPP_B }}
            - name: webapps_a
              targets:
                - ${{ secrets.LINODE_WEBAPP_A }}
            - name: webapps_b
              targets:
                - ${{ secrets.LINODE_WEBAPP_b }}
          config:
            transport: ssh
            ssh:
              host-key-check: false
              user: root
              private-key: id_rsa.pem
          EOF
      - name: Apply Changes to Webapps A
        run: bolt plan run pyapp::install -t webapps_a
      - name: Apply Changes to Webapps B
        run: bolt plan run pyapp::install -t webapps_b
